l_japanese:
 SETTINGS_PAGE_GRAPHICS:0 "グラフィック"
 SETTINGS_PAGE_GAME:0 "ゲーム"
 SETTINGS_PAGE_SYSTEM:0 "システム"
 SETTINGS_PAGE_CONTROLS:0 "コントロール"
 SETTINGS_PAGE_EDITOR:0 "エディター"
 SETTINGS_PAGE_INTERFACE:0 "インターフェイス"
 SETTINGS_PAGE_AUDIO:0 "オーディオ"
 SETTINGS_CATEGORY_SCREEN:0 "スクリーン"
 SETTINGS_CATEGORY_QUALITY:0 "品質"
 OPTION_EASY:0 "イージー"
 OPTION_NORMAL:0 "ノーマル"
 OPTION_HARD:0 "ハード"
 OPTION_NEVER:0 "ない"
 OPTION_MONTHLY:0 "毎月"
 OPTION_HALFYEAR:0 "半年に1度"
 OPTION_YEARLY:0 "毎年"
 OPTION_FIVE_YEAR:0 "5年に1度"
 OPTION_NO_AUTOSAVE:0 "自動セーブしない"
 SETTINGS_CATEGORY_ACCOUNT:0 "アカウント"
 SETTINGS_CATEGORY_SYSTEM:0 "システム"
 SETTINGS_CATEGORY_CONTROLS:0 "コントロール"
 SETTINGS_CATEGORY_CAMERA:0 "カメラ"
 SETTINGS_CATEGORY_AUDIO:0 "オーディオ"
 SETTINGS_CATEGORY_GUI:0 "GUI"
 SETTINGS_CATEGORY_INPUT_BINDINGS:0 "入力バインディング"
 DISCARD:0 "破棄"
 SAVE_AND_CLOSE:0 "OK"
 SETTINGS:0 "設定"
 REQUIRES_RESTART:0 "再起動が必要です"
 REQUIRE_RESTART_DESCRIPTION:0 "ゲームを再起動するまで一部の設定は適用されません"
 SETTINGS_INPUT_REMAP_INPUT:0 "再マップ入力"
 SETTINGS_INPUT_CONFIRM:0 "確認"
 SETTINGS_INPUT_CANCEL:0 "キャンセル"
 SETTINGS_INPUT_CLEAR:0 "消去"
 SETTINGS_INPUT_SAVE_INPUT_PROFILE:0 "プロフィールを保存"
 SETTINGS_INPUT_LOAD_INPUT_PROFILE:0 "プロフィールをロード"
 SETTINGS_INPUT_RESET_INPUT_PROFILE:0 "デフォルトにリセット"
 SETTINGS_INPUT_BINDING_TEXT:0 "'$INPUT_ACTION$' アクションの入力バインディングを選択してください : \n\n$INPUT_NAME$"
 SETTINGS_INPUT_BINDING_WARNING_TEXT:0 "警告 : この入力バインディングは '$INPUT_ACTION$' にすでに存在しています！\n'$SETTINGS_INPUT_CONFIRM$' を押すと古いバインディングを消去します"
