l_english:
 SETTING_VALUE_WARNING: "$VALUE|0X$"
 SETTING_VALUE_PERCENTAGE_WARNING: "$VALUE|%0X$"
 RECOMMENDED_GUI_SCALE_TOO_HIGH: "#X Scaling above $VALUE|%0$ will cause interfaces to appear outside the screen#!"
 RECOMMENDED_GUI_SCALE: "Scaling above $VALUE|%0$ will cause interfaces to appear outside the screen"
