l_english:
 # General 
 SETTING_VALUE_NONE: "$VALUE$"
 SETTING_VALUE_TOTAL_PERCENTAGE: "$VALUE|%/0$"
 SETTING_VALUE_PERCENTAGE: "$VALUE|%0$"
 SETTING_VALUE_SECONDS: "$VALUE$ seconds"
 SETTING_VALUE_MINUTES: "$VALUE$ minutes"
 # Graphics
 SETTING_RENDERER: "Renderer"
 SETTING_RENDERER_TOOLTIP: "Determines which renderer is being used."
 SETTING_VSYNC: "VSync"
 SETTING_VSYNC_TOOLTIP: "#T $SETTING_VSYNC$\n#!Makes the game and your monitor have the same frame rate, reducing screen tearing.\n\nTurning it off may increase performance."
 SETTING_PORTRAIT_MULTI_SAMPLING: "Portrait MultiSampling"
 SETTING_PORTRAIT_MULTI_SAMPLING_TOOLTIP: "#T $SETTING_PORTRAIT_MULTI_SAMPLING$\n#!Using multi-sample for Alpha-To-Coverage to make hair blending smoother.\n\nLower settings increase performance."
 SETTING_MULTI_SAMPLING: "Anti-aliasing (MSAA)"
 SETTING_MULTI_SAMPLING_TOOLTIP: "#T $SETTING_MULTI_SAMPLING$\n#!Using multi-sample anti-aliasing (MSAA) will make edges of images smoother.\n\nLower settings may increase performance."
 SETTING_ANTI_ALIASING: "Anti-Aliasing"
 SETTING_ANTI_ALIASING_TOOLTIP: "#T $SETTING_ANTI_ALIASING$\n#!Using anti-aliasing will make edges of images smoother.\n\nFXAA is recommended."
 OPTION_ANTI_ALIASING_DISABLED: "Disabled"
 OPTION_ANTI_ALIASING_FXAA: "FXAA"
 SETTING_UPSCALE: "Upscale Method"
 SETTING_UPSCALE_TOOLTIP: "#T $SETTING_UPSCALE$#!\nUpscale methods can be used to achieve higher display resolution through algorithmic upsampling. This may improve performance but can result in visual artifacts or other unexpected behavior.\n\nAvailable upscale methods may depend on your graphics card."
 OPTION_UPSCALE_FSR2: "AMD FidelityFX Super Resolution 2"
 OPTION_UPSCALE_DLSS: "NVIDIA DLSS"
 OPTION_UPSCALE_XESS: "Intel® XeSS"
 SETTING_UPSCALE_QUALITY: "Upscale Quality"
 SETTING_UPSCALE_QUALITY_TOOLTIP: "#T $SETTING_UPSCALE_QUALITY$#!\nSets the focus of the upscaling method from targeting highest quality to targeting highest performance."
 OPTION_UPSCALE_QUALITY_ULTRA_QUALITY: "Ultra Quality"
 OPTION_UPSCALE_QUALITY_QUALITY: "Quality"
 OPTION_UPSCALE_QUALITY_BALANCED: "Balanced"
 OPTION_UPSCALE_QUALITY_PERFORMANCE: "Performance"
 OPTION_UPSCALE_QUALITY_ULTRA_PERFORMANCE: "Ultra Performance"
 SETTING_ANISOTROPIC_FILTERING: "Texture Filtering"
 SETTING_ANISOTROPIC_FILTERING_TOOLTIP: "#T $SETTING_ANISOTROPIC_FILTERING$\n#!Using anisotropic filtering will make textured surfaces look better.\n\nLower settings may increase performance."
 SETTING_FULLSCREEN_RESOLUTION: "Resolution"
 SETTING_FULLSCREEN_RESOLUTION_TOOLTIP: "#T $SETTING_FULLSCREEN_RESOLUTION$\n#!Sets the image quality of the game.\n\nLower Resolutions may increase performance.\n\n#X Game resolution with unsupported aspect ratio may cause interfaces to appear outside the screen#!"
 SETTING_WINDOWED_RESOLUTION: "Windowed Resolution"
 SETTING_WINDOWED_RESOLUTION_TOOLTIP: "#T $SETTING_WINDOWED_RESOLUTION$\n#!Sets the resolution of the game window if the game is in Windowed Mode.\n\nMust be in the format #b NUMBER#!x#b NUMBER#!.\n\n#X Game resolution with unsupported aspect ratio may cause interfaces to appear outside the screen#!"
 SETTING_RENDER_SCALE: "Render Scale"
 SETTING_RENDER_SCALE_TOOLTIP: "#T $SETTING_RENDER_SCALE$#!\nThe scale of the render resolution of the game relative to the main resolution, excluding the user interface.\n\nLower settings may increase performance but will reduce overall fidelity, while going above 100% may increase fidelity but will likely degrade performance."
 SETTING_RENDER_SCALE_FORMAT: "$VALUE|%0$"
 SETTING_DISPLAY: "Monitor"
 SETTING_DISPLAY_TOOLTIP: "#T $SETTING_DISPLAY$\n#!If your computer has multiple monitors, choose the one to be used by the game."
 SETTING_GRAPHICS_DEVICE: "Graphics Card"
 SETTING_GRAPHICS_DEVICE_TOOLTIP: "#T $SETTING_GRAPHICS_DEVICE$\n#!Selects which graphics card the game will use. \n\nUsing an integrated graphics card or software renderer may decrease performance."
 SETTING_SHADOW_MAP_RESOLUTION: "Shadow Quality"
 SETTING_SHADOW_MAP_RESOLUTION_TOOLTIP: "#T $SETTING_SHADOW_MAP_RESOLUTION$\n#!Determines the resolution shadow maps are rendered with, if shadows are enabled.\n\nLower settings may increase performance."
 SETTING_DISPLAY_MODE: "Display Mode"
 SETTING_DISPLAY_MODE_TOOLTIP: "#T $SETTING_DISPLAY_MODE$\n#!Determines how to display the game on your screen"
 SETTING_BLOOM: "Bloom"
 SETTING_MESH_LOD_BIAS: "Mesh LOD Quality"
 SETTING_MESH_LOD_FADE: "Mesh LOD Fade"
 SETTING_TERRAIN_SMOOTHING: "Terrain Smoothing"
 OPTION_FULLSCREEN: "Fullscreen"
 OPTION_FULLSCREEN_TOOLTIP: "#T $OPTION_FULLSCREEN$\n#!Display the game using the entire screen. The Resolution setting will change how sharp the image will be."
 OPTION_WINDOWED: "Window"
 OPTION_WINDOWED_TOOLTIP: "#T $OPTION_WINDOWED$\n#!Display the game in a window. The Resolution setting changes the size of the window."
 OPTION_DISABLED: "Disabled"
 OPTION_OFF: "Off"
 OPTION_LOW: "Low"
 OPTION_MEDIUM: "Medium"
 OPTION_HIGH: "High"
 OPTION_ULTRA: "Ultra"
 OPTION_CUSTOM: "Custom"
 OPTION_DEFAULT: "Default"
 SETTINGS_CATEGORY_UI: "Interface"
 SETTINGS_CATEGORY_GAME: "Game"
 SETTING_TEXTURE_QUALITY: "Texture Quality"
 SETTING_TEXTURE_QUALITY_TOOLTIP: "#T $SETTING_TEXTURE_QUALITY$#!\nControls the resolution of textures loaded.\n\nLower settings may increase performance."
 SETTING_QUALITY: "Quality Preset"
 SETTING_SFX: "SFX"
 SETTING_UI: "Interface"
 SETTING_QUALITY_TOOLTIP: "#T $SETTING_QUALITY$\n#!Select a preset of the advanced graphics options below.\n\nA low preset will increase performance."
 SETTING_BLOOM_TOOLTIP: "#T $SETTING_BLOOM$\n#!Enables a "bloom" effect, where extremely bright lights will spill over to other parts of the image.\n\nTurning it off may increase performance."
 SETTING_DOF_TOOLTIP: "#T $SETTING_DOF$\n#!Enables depth of field to simulate a camera lens, blurs out-of-focus points of the image.\n\nTurning it off may increase performance."
 SETTING_LENS_FLARE_TOOLTIP: "#T $SETTING_LENS_FLARE$\n#!Enables a lens flare effect which appears in highly blooming areas. Bloom must be enabled for the effect to appear. \n\nTurning it off may increase performance."
 SETTING_SECONDARY_LENS_FLARE_TOOLTIP: "#T $SETTING_SECONDARY_LENS_FLARE$\n#!Enables a secondary lens flare effect which appears in highly blooming areas. Bloom must be enabled for the effect to appear. \n\nTurning it off may increase performance."
 SETTING_MAP_SSAO_TOOLTIP: "#T $SETTING_MAP_SSAO$\n#!Determines whether screen space ambient occlusion should be applied to the map.\n\nTurning it off may increase performance."
 SETTING_REFRACTION_TOOLTIP: "Determines whether refractions appear on water or not."
 SETTING_REFRACTION_QUALITY_TOOLTIP: "#T $SETTING_REFRACTION_QUALITY$#!\nControls the quality of water refractions if they are enabled.\n\nLower settings may increase performance."
 SETTING_MAPOBJECT_QUALITY_TOOLTIP: "#T $SETTING_MAPOBJECT_QUALITY$#!\nDetermines the highest quality level of Map Objects (such as buildings).\n\nLower settings may increase performance."
 SETTING_MESH_LOD_BIAS_TOOLTIP: "#T $SETTING_MESH_LOD_BIAS$#!\nDetermines the quality of LODs (Levels of detail) on map objects such as Unit models.\n\nLower settings may increase performance."
 SETTING_MESH_LOD_FADE_TOOLTIP: "#T $SETTING_MESH_LOD_FADE$\n#!If turned on, 3D models smoothly transition between different levels of detail (LOD) when you zoom in or out.\n\nTurning it off may increase performance."
 SETTING_PROVINCE_NAMES_TOOLTIP: "Determines how City and Province names appear on the map."
 SETTING_FILL_IN_IMPASSABLE_TERRAIN_TOOLTIP: "Determines if impassable terrain is included within a nation's borders on the map."
 SETTING_LANGUAGE_TOOLTIP: "#T $SETTING_LANGUAGE$#!\nDetermines the Language of the User Interface."
 SETTING_ACCOUNT_EMAIL_TOOLTIP: "Your Paradox Account email"
 SETTING_FRAMERATE_CAP: "Maximum FPS"
 SETTING_FRAMERATE_CAP_TOOLTIP: "#T $SETTING_FRAMERATE_CAP$#!\nMaximum FPS (Frames per second) that the game will render.\n\nLower settings may decrease power consumption."
 OPTION_CAP_30: "30"
 OPTION_CAP_60: "60"
 OPTION_CAP_90: "90"
 OPTION_CAP_120: "120"
 OPTION_CAP_144: "144"
 OPTION_CAP_165: "165"
 SETTING_TEXTURE_STREAMING: "Texture Streaming"
 SETTING_TEXTURE_STREAMING_TOOLTIP: "#T $SETTING_TEXTURE_STREAMING$#!\nTextures are loaded in as needed.\n\nLowers GPU memory usage at the cost of some CPU time overhead. May increase performance for GPU's with a small amount of memory."
 SETTING_TEXTURE_STREAMING_CACHE: "Texture Streaming Cache Size"
 SETTING_VALUE_MB: "$VALUE$ MB"
 # GUI
 SETTING_ANIMATION_SPEED: "Animation speed"
 SETTING_GUI_SCALING: "GUI Scaling"
 SETTING_GUI_SCALING_TOOLTIP: "#T $SETTING_GUI_SCALING$\n#!Sets the scale of the entire user interface. Useful for higher screen resolutions.\n\n#X Setting it too high will make interfaces not properly fit inside the screen!#!"
 # System
 SETTING_SCREEN_EDGE_SCROLL_MODE: "Mouse Pan"
 SETTING_SCREEN_EDGE_SCROLL_MODE_FREE: "Free"
 SETTING_SCREEN_EDGE_SCROLL_MODE_8_DIRECTIONS: "8 directions"
 SETTING_SCREEN_EDGE_SCROLL_DISABLED: "Disabled"
 SETTING_SCREEN_EDGE_SCROLL_MODE_TOOLTIP: "#T $SETTING_SCREEN_EDGE_SCROLL_MODE$#!\nHow the camera behaves when panning with the mouse."
 SETTING_SCROLL_SPEED: "Pan Speed"
 SETTING_SCROLL_SPEED_TOOLTIP: "#T $SETTING_SCROLL_SPEED$#!\nSets how fast the map pans when using the keyboard or the mouse."
 SETTING_CAMERA_ROTATION_SPEED: "Camera Rotation Speed"
 SETTING_CAMERA_ROTATION_SPEED_TOOLTIP: "#T $SETTING_CAMERA_ROTATION_SPEED$#!\nThe camera rotation speed."
 SETTING_ZOOM_SPEED: "Zoom Speed"
 SETTING_ZOOM_SPEED_TOOLTIP: "#T $SETTING_ZOOM_SPEED$#!\nThe camera zoom speed."
 SETTING_MOUSE_CURSOR_ZOOM_MODE: "Zoom Behavior"
 SETTING_MOUSE_CURSOR_ZOOM_MODE_RELATIVE_CURSOR: "Relative cursor"
 SETTING_MOUSE_CURSOR_ZOOM_MODE_ZOOM_IN_TO_CURSOR: "Zoom in to cursor"
 SETTING_MOUSE_CURSOR_ZOOM_MODE_IGNORE_CURSOR: "Ignore cursor"
 SETTING_MOUSE_CURSOR_ZOOM_MODE_TOOLTIP: "#T $SETTING_MOUSE_CURSOR_ZOOM_MODE$#!\nHow the camera behaves relative to the mouse cursor when zooming in/out."
 SETTING_INPUT_DEVICE: "Input device"
 SETTING_EDITOR: "Editor"
 SETTING_EDITOR_POSTFIX: "Editor postfix"
 SETTING_EDITOR_OPEN_FILE_FORMAT: "Editor open command"
 SETTING_LOG_VIEWER_OPEN_FILE_FORMAT: "View log command"
 SETTING_CODE_EDITOR_OPEN_FILE_FORMAT: "Code editor open command"
 SETTING_GRACEFUL_EXIT: "Graceful exit"
 SETTING_LANGUAGE: "Language"
 MOUSE_AND_KEYBOARD: "Mouse and keyboard"
 GAMEPAD: "Gamepad"
 SETTING_MULTISAMPLING_DISABLED: "Disabled"
 SETTING_PORTRAIT_MULTISAMPLING_DISABLED: "Disabled"
 SETTING_ANISOTROPIC_FILTERING_DISABLED: "Disabled"
 # Editor
 SETTING_CAMERA_TILT: "Camera tilt"
 SETTING_CAMERA_STRATEGY: "Camera type"
 SETTING_CENTERED_ZOOM_IN: "Centered zoom-in"
 SETTING_CAMERA_SPEED: "Camera speed"
 CAMERA_TABLETOP: "Table top"
 CAMERA_FPS: "First person"
 CAMERA_WASD: "WASD-style"
 # Audio
 SETTING_Music: "Music"
 SETTING_Ambient: "Ambient"
 SETTING_Effects: "Effects"
 SETTING_Master: "Master"
 SETTING_VO: "Voice-Over"
 SETTING_VO_TOOLTIP: "#T Voice-over Volume\n#!Sets the volume of voice-over audio in the game."
 SETTING_Master_TOOLTIP: "#T Master Volume\n#!Sets the volume of all sounds in the game."
 SETTING_Music_TOOLTIP: "#T Music Volume\n#!Sets the volume of the music."
 SETTING_Ambient_TOOLTIP: "#T Ambient Volume\n#!Sets the volume of environmental ambience."
 SETTING_SFX_TOOLTIP: "#T SFX Volume\n#!Sets the volume of sound effects such as combat."
 SETTING_UI_TOOLTIP: "#T Interface Volume\n#!Sets the volume of the user interface."
 SETTING_AUDIO_DEBUG_LOG_LEVEL: "Debug Log Level"
 SETTING_AUDIO_DEVICE_PROFILE: "Audio Profile"
 SETTING_AUDIO_DEVICE_PROFILE_TOOLTIP: "#T $SETTING_AUDIO_DEVICE_PROFILE$\n#!Choose the audio profile that fits your setup."
 SETTING_AUDIO_OPTION_SPEAKERS: "Speakers"
 SETTING_AUDIO_OPTION_SPEAKERS_TOOLTIP: "#T $SETTING_AUDIO_OPTION_SPEAKERS$\n#!Default mix for $SETTING_AUDIO_OPTION_SPEAKERS$."
 SETTING_AUDIO_OPTION_HEADPHONES: "Headphones"
 SETTING_AUDIO_OPTION_HEADPHONES_TOOLTIP: "#T $SETTING_AUDIO_OPTION_HEADPHONES$\n#!Mix adjusted for $SETTING_AUDIO_OPTION_HEADPHONES$."
 SETTING_AUDIO_OPTION_TV: "TV"
 SETTING_AUDIO_OPTION_TV_TOOLTIP: "#T $SETTING_AUDIO_OPTION_TV$\n#!Mix for $SETTING_AUDIO_OPTION_TV$ and monitor speakers."
 SETTING_AUDIO_OPTION_NIGHTMODE: "Night Mode"
 SETTING_AUDIO_OPTION_NIGHTMODE_TOOLTIP: "#T $SETTING_AUDIO_OPTION_NIGHTMODE$\n#!Softens the sound for night play, dimming higher pitches and compressing the dynamic range."
 SETTING_MUSIC_DENSITY: "Music Density"
 SETTING_MUSIC_DENSITY_TOOLTIP: "Controls the balance between full songs, silence and mood music segments.\n\nIntense = Mostly songs playing one after the other, similar to a ‘radio station’.\nBalanced = The perfect balance between songs, silence, and mood setting\nRelaxed = Mostly relaxing music segments that provide a better mood experience and less sense of repetition after several hours of playing”"
  # Game
 SETTING_AUTOSAVE: "Autosave Interval"
 SETTING_AUTOSAVE_TOOLTIP: "#T $SETTING_AUTOSAVE$\n#!Sets how often the game will save automatically."
 SETTING_AUTOSAVE_TO_CLOUD_TOOLTIP: "Determines whether Autosaves are saved to the cloud or not."
 SETTING_CAMERA_FACE_NORTH_TOOLTIP: "Determines whether the Camera will always face North or not."
 NO_AUTOSAVE: "No Autosave"
 # Multiplayer
 SETTINGS_FILE_TRANSFER_SPEED: "File Transfer Speed"
 SETTINGS_FILE_TRANSFER_SPEED_TOOLTIP: "#T $File Transfer Speed$\n#!Sets the maximum speed for save game file transfers in the multiplayer lobby.\n\nLower settings might improve network stability of joining multiplayer games but have a negative effect on multiplayer load times."
 # Tools
 SETTING_MAP_EDITOR_AUTOSAVE_INTERVAL_MINUTES: "Map Editor Auto-save (minutes)"
 SETTING_MAP_EDITOR_AUTOSAVE_INTERVAL_MINUTES_TOOLTIP: "Map Editor Auto-save interval (minutes)"
 SETTING_NODE_EDITOR_DRAG_PAN_MODE: "Node Editor Drag Pan Mode"
 # Accessibility
 SETTINGS_CATEGORY_ACCESSIBILITY: "Accessibility"
 SETTING_COLOR_BLIND_MODE: "Color Blind Mode"
 SETTING_COLOR_BLIND_MODE_TOOLTIP: "#T $SETTING_COLOR_BLIND_MODE$\n#!Changes the colors used in text throughout the game to a set of colors that is easier to distinguish for different types of color blindness."
