l_japanese: SETTINGS_PAGE_GRAPHICS:1 "グラフィック"
 SETTINGS_PAGE_GAME:1 "ゲーム"
 SETTINGS_PAGE_SYSTEM:1 "システム"
 SETTINGS_PAGE_CONTROLS:1 "コントロール"
 SETTINGS_PAGE_EDITOR:1 "エディター"
 SETTINGS_PAGE_INTERFACE:1 "インターフェイス"
 SETTINGS_PAGE_AUDIO:1 "オーディオ"
 SETTINGS_CATEGORY_SCREEN:1 "スクリーン"
 SETTINGS_CATEGORY_QUALITY:1 "品質"
 OPTION_EASY:1 "イージー"
 OPTION_NORMAL:1 "ノーマル"
 OPTION_HARD:1 "ハード"
 OPTION_NEVER:1 "ない"
 OPTION_MONTHLY:1 "毎月"
 OPTION_HALFYEAR:1 "半年に1度"
 OPTION_YEARLY:1 "毎年"
 OPTION_FIVE_YEAR:1 "5年に1度"
 OPTION_NO_AUTOSAVE:1 "自動セーブしない"
 SETTINGS_CATEGORY_ACCOUNT:1 "アカウント"
 SETTINGS_CATEGORY_SYSTEM:1 "システム"
 SETTINGS_CATEGORY_CONTROLS:1 "コントロール"
 SETTINGS_CATEGORY_CAMERA:1 "カメラ"
 SETTINGS_CATEGORY_AUDIO:1 "オーディオ"
 SETTINGS_CATEGORY_GUI:1 "GUI"
 SETTINGS_CATEGORY_INPUT_BINDINGS:1 "入力バインディング"
 DISCARD:1 "破棄"
 SAVE_AND_CLOSE:1 "OK"
 SETTINGS:1 "設定"
 REQUIRES_RESTART:1 "再起動が必要です"
 REQUIRE_RESTART_DESCRIPTION:1 "ゲームを再起動するまで一部の設定は適用されません"
 SETTINGS_INPUT_REMAP_INPUT:1 "再マップ入力"
 SETTINGS_INPUT_CONFIRM:1 "確認"
 SETTINGS_INPUT_CANCEL:1 "キャンセル"
 SETTINGS_INPUT_CLEAR:1 "消去"
 SETTINGS_INPUT_SAVE_INPUT_PROFILE:1 "プロフィールを保存"
 SETTINGS_INPUT_LOAD_INPUT_PROFILE:1 "プロフィールをロード"
 SETTINGS_INPUT_RESET_INPUT_PROFILE:1 "デフォルトにリセット"
 SETTINGS_INPUT_BINDING_TEXT:1 "'$INPUT_ACTION$' アクションの入力バインディングを選択してください: \n\n$INPUT_NAME$"
 SETTINGS_INPUT_BINDING_WARNING_TEXT:1 "警告: この入力バインディングは '$INPUT_ACTION$' にすでに存在しています！\n'$SETTINGS_INPUT_CONFIRM$' を押すと古いバインディングを消去します"
