l_japanese:
 SETTING_REFRACTION: "屈折"
 SETTING_REFRACTION_QUALITY: "屈折品質"
 SETTING_MAPOBJECT_QUALITY: "マップオブジェクト"
 SETTING_MAP_SSAO: "マップSSAO"
 SETTING_DOF: "被写界深度"
 SETTING_LENS_FLARE: "レンズフレア"
 SETTING_SECONDARY_LENS_FLARE: "二次レンズフレア"
