l_japanese: pm_primary:1 "一次"
 pmg_secondary_building_rye_farm:1 "二次"
 pmg_secondary_building_wheat_farm:1 "二次"
 pmg_secondary_building_rice_farm:1 "二次"
 pmg_secondary_building_maize_farm:1 "二次"
 pmg_secondary_building_millet_farm:1 "二次"
 pm_no_secondary:1 "単一の作物を維持"
 pm_potatoes:1 "ジャガイモ"
 pm_vineyards:1 "ブドウ畑"
 pm_vineyards_building_maize_farm:1 "ブドウ畑"
 pm_apple_orchards:1 "リンゴ園"
 pm_citrus_orchards:1 "柑橘園"
 pm_fig_orchards:1 "イチジク園"
 pm_mulberry_groves:1 "マルベリーグローブ"
 pmg_automation:1 "自動化"
 pmg_automation_building_food_industry:1 "自動化"
 pmg_automation_building_textile_mills:1 "自動化"
 pmg_automation_building_furniture_manufacturies:1 "自動化"
 pmg_automation_building_tooling_workshops:1 "自動化"
 pmg_automation_building_paper_mills:1 "自動化"
 pmg_automation_building_steel_mills:1 "自動化"
 pmg_automation_building_motor_industry:1 "自動化"
 pm_civilian_priority:1 "民間優先"
 pm_military_priority:1 "軍事優先"
 pm_craftsman_sewing:1 "職人による縫製"
 pm_sewing_machines:1 "ミシン"
 pm_electric_sewing_machines:1 "電動ミシン"
 pm_traditional_looms:1 "従来型織機"
 pm_mechanized_looms:1 "機械式織機"
 pm_automatic_power_looms:1 "自動力織機"
 pm_leaded_glass:1 "有鉛ガラス"
 pm_manual_glassblowing:1 "手動吹きガラス"
 pm_leblanc_process:1 "ルブラン法"
 pm_no_explosives_production:1 "肥料生産を優先"
 pm_ammonia-soda_process:1 "アンモニアソーダ法"
 pm_vacuum_evaporation:1 "真空蒸着"
 pm_brine_electrolysis:1 "食塩電解"
 pmg_fertilizer_production:1 "肥料生産"
 pm_no_artificial_fertilizers:1 "人工肥料不可"
 pm_artificial_fertilizers:1 "人工肥料"
 pm_improved_fertilizer:1 "改良肥料"
 pm_nitrogen_fixation:1 "窒素固定法"
 pm_dyes_production:1 "染料生産"
 pm_no_synthetic_dyes:1 "合成染料不可"
 pmg_synthetic_dyes:1 "合成染料"
 pm_silk_production:1 "絹生産"
 pm_no_artificial_fibers:1 "染料生産を優先"
 pm_rayon:1 "レーヨン"
 pm_steamworks:1 "蒸気製法"
 pm_no_artillery_production:1 "小火器生産を優先"
 pm_artillery_production:1 "大砲生産"
 pmg_automobile_production:1 "車両生産"
 pm_automobile_production:1 "車両生産"
