l_japanese:
 SETTING_AUTOSAVE_TO_CLOUD:0 "クラウドにオートセーブ"
 SETTING_SAVE_FILE_FORMAT:0 "デフォルトセーブ形式"
 SETTING_SAVE_FILE_FORMAT_TOOLTIP:0 "このオプションは鉄人、クラウド、デバッグモードで上書きされます"
 OPTION_SAVE_FILE_TEXT:0 "テキスト"
 OPTION_SAVE_FILE_ZIP_TEXT_ALL:0 "ZIPテキスト"
 OPTION_SAVE_FILE_ZIP_BINARY_ALL:0 "ZIPバイナリ"
 SETTING_TOOLTIP_MODE:0 "ツールチップモード"
 SETTING_TOOLTIP_MODE_TOOLTIP:0 "#T $SETTING_TOOLTIP_MODE$#!\nツールチップのロック方法を選択します : \n   #b マウス挙動#!ツールチップにカーソルを移動させるとロックします。\n   #b タイマーロック#!一定時間が経過するとロックします。\n   #b アクションロック#!マウスの中ボタンでロックします。\n   #b タイマーかアクションロック#! ―タイマーロックまたはアクションロックを使用できます。"
 SETTING_TOOLTIP_MODE_NO_LOCK:0 "ロックなし"
 SETTING_TOOLTIP_MODE_MOUSE_TENDENCY:0 "マウス性質"
 SETTING_TOOLTIP_MODE_LOCK_ON_ACTION_MOUSE_ANCHOR:0 "アクションロック (マウスアンカー) "
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER_MOUSE_ANCHOR:0 "タイマーロック (マウスアンカー) "
 SETTING_TOOLTIP_MODE_LOCK_ON_ACTION_WIDGET_ANCHOR:0 "アクションロック"
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER_WIDGET_ANCHOR:0 "タイマーロック"
 SETTING_TOOLTIP_DELAY_TOOLTIP:0 "#T $SETTING_TOOLTIP_DELAY$#!\nツールチップを備えたエレメントにマウスオーバーした際の表示遅延を設定します。"
 SETTING_TOOLTIP_DELAY:0 "遅延表示"
 SETTING_TOOLTIP_UNLOCK_TIME:0 "遅延ロック解除"
 SETTING_TOOLTIP_UNLOCK_TIME_TOOLTIP:0 "#T $SETTING_TOOLTIP_UNLOCK_TIME$#!\nツールチップのロックが解除されるまでの時間を設定します。"
 SETTING_TOOLTIP_LOCK_TIME:0 "遅延ロック"
 SETTING_TOOLTIP_LOCK_TIME_TOOLTIP:0 "#T $SETTING_TOOLTIP_LOCK_TIME$#!\nツールチップがロックされるまでの時間を設定します。"
 SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED:0 "遅延ロックオープン"
 SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED_TOOLTIP:0 "#T $SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED$#!\n他のツールチップがすでに開いているときに、ツールチップがロックされるまでの時間を設定します。"
 SETTINGS_CATEGORY_ADVANCED_GRAPHICS:0 "上級"
 SETTINGS_CATEGORY_AUDIO_GENERAL:0 "一般"
 SETTINGS_CATEGORY_SFX:0 "効果音"
 SETTINGS_CATEGORY_LANGUAGE:0 "言語"
 SETTINGS_CATEGORY_SAVE_GAMES:0 "ゲームをセーブ"
 SETTINGS_CATEGORY_TOOLTIPS:0 "ツールチップ設定"
 SETTINGS_CATEGORY_MAP_CONTROLS:0 "マップ操作"
 SETTING_SHADER_QUALITY:0 "シェーダー品質"
 SETTING_SHADER_QUALITY_TOOLTIP:0 "#T シェーダー品質\n#!各種シェーダーやエフェクトの品質を決定します。\n\n#T 高 : #! パフォーマンスを犠牲にして一部のシェーダーエフェクトの品質を向上させます。\n\n#T 中#! 意図したグラフィック体験のためのデフォルト設定です。\n\n#T 低#! この設定はローエンドのマシン用に作られており、ビジュアル品質が低下するため推奨されません。複数のシェーダーを簡略化して、グラフィックパフォーマンスを向上させます。"
 SETTING_SHOW_NUDITY:0 "裸体を表示"
 SETTING_SHOW_NUDITY_TOOLTIP:0 "#T $SETTING_SHOW_NUDITY$#!\nキャラクターの裸体を表示するかどうかを設定します。"
 SETTINGS_CATEGORY_GAME_PORTRAITS:0 "ポートレート"
 SETTING_MUSIC:0 "音楽"
 SETTING_AMBIENT:0 "環境音楽"
 SETTING_MUSIC_TOOLTIP:0 "#T 音楽の音量\n#!音楽の音量を設定します。"
 SETTING_AMBIENT_TOOLTIP:0 "#T 環境音楽の音量\n#!環境音楽の音量を設定します。"
 color_blind_mode_test:0 "テスト"
 SETTINGS_CATEGORY_MFX:0 "音楽"
 SETTING_SOUNDTRACK:0 "BGM"
 SETTING_SOUNDTRACK_TOOLTIP:0 "BGM全般"
 SETTING_MUSIC_STINGERS:0 "スティンガー曲"
 SETTING_MUSIC_STINGERS_TOOLTIP:0 "ゲームプレイを盛り上げる短い音楽のフレーズ"
 SETTING_MAP_TOOLTIP_DELAY:0 "マップのツールチップの遅延"
 SETTING_MAP_TOOLTIP_DELAY_TOOLTIP:0 "#T $SETTING_MAP_TOOLTIP_DELAY$#!\nマップのツールチップが表示されるまでの時間を表示します。"
 SETTINGS_CATEGORY_MAPMODES:0 "マップモード"
 SETTING_MAP_MODE_DELAY:0 "マップモードの遅延"
 SETTING_MAP_MODE_DELAY_TOOLTIP:0 "新しいマップモードに切り替えるまでの遅延 (秒単位) "
 SETTING_MAP_MODE_FADE_IN:0 "マップモードのフェードイン"
 SETTING_MAP_MODE_FADE_IN_TOOLTIP:0 "古いマップモードがフェードアウトした後、新しいマップモードがフェードインする時間 (秒単位) "
 SETTING_MAP_MODE_FADE_OUT:0 "マップモードのフェードアウト"
 SETTING_MAP_MODE_FADE_OUT_TOOLTIP:0 "新しいマップモードが適用された際、マップモードの遅延の後に現在のマップモードがフェードアウトする時間 (秒単位) "
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER_OR_ACTION_WIDGET_ANCHOR:0 "タイマーかアクションロック"
 SETTING_OCCUPATION_STRIPES:0 "縞模様の占領ビジュアル"
 SETTING_OCCUPATION_STRIPES_TOOLTIP:0 "#T $SETTING_OCCUPATION_STRIPES$#!\n地図上の占領ビジュアルとして、国旗テクスチャの代わりに色付きの縞模様を使用するようにします。"
 SETTING_VALUE_HOURS:0 "$VALUE|0$時間"
 SETTING_VALUE_HOUR_FULL:0 "$VALUE|0$ : 00"
 SETTINGS_CATEGORY_DAYNIGHT_CYCLE:0 "昼夜の移り変わり"
 SETTING_DAYNIGHT_CYCLE:0 "昼夜の移り変わりを有効化"
 SETTING_DAYNIGHT_CYCLE_TOOLTIP:0 "#T $SETTING_DAYNIGHT_CYCLE$#!\n太陽の動きに合わせた昼夜の移り変わりを有効にします。"
 SETTING_DAYNIGHT_SYSTEMTIME:0 "ローカルタイムとの同期を有効化"
 SETTING_DAYNIGHT_SYSTEMTIME_TOOLTIP:0 "#T $SETTING_DAYNIGHT_SYSTEMTIME$#!\n昼夜の移り変わりの速度と時間を、コンピューターのローカルタイムに同期させます。\n\n#!シミュレーション速度の設定を上書きします。"
 SETTING_DAYNIGHT_SPEED:0 "シミュレーション速度"
 SETTING_DAYNIGHT_SPEED_TOOLTIP:0 "#T $SETTING_DAYNIGHT_SPEED$#!\n昼夜の移り変わりの速さを決定します。#"
 SETTING_SUN_DURATION:0 "日照時間"
 SETTING_SUN_DURATION_TOOLTIP:0 "#T $SETTING_SUN_DURATION$#!\n1日の日照時間を決定します。"
 SETTING_SUNRISE_TIME:0 "日の出時刻"
 SETTING_SUNRISE_TIME_TOOLTIP:0 "#T $SETTING_SUNRISE_TIME$#!\n太陽が昇る時刻を決定します。\n\n#!ローカルタイムと同期している場合にのみ使用します。#!"
 SETTING_DAYNIGHT_SET_TIME:0 "手動時間を有効化"
 SETTING_DAYNIGHT_SET_TIME_TOOLTIP:0 "#T $SETTING_DAYNIGHT_SET_TIME$#!\n時間を指定の時刻に設定します。\n\n#!シミュレーション速度とローカルタイムの同期の設定を上書きします。"
 SETTING_SUNRISE_SET_TIME_HOUR:0 "手動時間の時刻"
 SETTING_SUNRISE_SET_TIME_HOUR_TOOLTIP:0 "#T $SETTING_SUNRISE_SET_TIME_HOUR$#!\n時間をこの時刻に固定します。\n\n#!手動時間が有効な場合にのみ使用します。#"
 SETTING_BUILDINGS_CUTOFF:0 "遠くの建物を間引く"
 SETTING_BUILDINGS_CUTOFF_TOOLTIP:0 "#T $SETTING_BUILDINGS_CUTOFF$#!\nカメラまでの距離が離れているほど、マップ上に表示される建物の数が少なくなります。\n\nこの設定を有効にするとパフォーマンスが向上することがあります。"
 ui_skin_theme:0 "ユーザーインターフェース"
 ui_skin_theme_desc:0 "ゲーム内のボタンやフレーム、ウィンドウ、ヘッダーなど。"
 papermap_theme:0 "紙の地図"
 papermap_theme_desc:0 "ズームアウトした際に表示される地図です。"
 table_top_theme:0 "机の天板"
 table_top_theme_desc:0 "マップで最大までズームアウトすると、画面の上下にこの机が表示されます。"
 table_asset_1_theme:0 "机のオブジェクト (左上) "
 table_asset_1_theme_desc:0 "ズームアウト時にマップ横の机の左上に表示されるオブジェクト。"
 table_asset_2_theme:0 "机のオブジェクト (右上) "
 table_asset_2_theme_desc:0 "ズームアウト時にマップ横の机の右上に表示されるオブジェクト。"
 table_asset_3_theme:0 "机のオブジェクト (左下) "
 table_asset_3_theme_desc:0 "ズームアウト時にマップ横の机の左下に表示されるオブジェクト。"
 table_asset_4_theme:0 "机のオブジェクト (右下) "
 table_asset_4_theme_desc:0 "ズームアウト時にマップ横の机の右下に表示されるオブジェクト。"
 building_sets_themes:0 "建物のセット"
 SETTING_PORTRAIT_RENDER_SCALE:0 "肖像の描画スケーリング"
 SETTING_PORTRAIT_RENDER_SCALE_TOOLTIP:0 "#T $SETTING_PORTRAIT_RENDER_SCALE$#!\n描画結果をアップサンプリングすることで、キャラクターの肖像画の詳細度は高まりますが、描画パフォーマンスが少し低下します。"
 OPTION_PORTRAIT_RENDER_SCALE_NONE:0 "×1.0 ―なし"
 OPTION_PORTRAIT_RENDER_SCALE_MEDIUM:0 "×1.5 ―中"
 OPTION_PORTRAIT_RENDER_SCALE_HIGH:0 "×2.0 ―高"
 SETTINGS_CATEGORY_OUTLINER:0 "アウトライナー"
 SETTING_SHOW_NOTIFICATION_FEED_NEXT_TO_OUTLINER:0 "アウトライナーの左に通知"
 SETTING_SHOW_NOTIFICATION_FEED_NEXT_TO_OUTLINER_TOOLTIP:0 "#t $SETTING_SHOW_NOTIFICATION_FEED_NEXT_TO_OUTLINER$#!\nアウトライナーの左に通知フィードを配置"
 SETTING_PAUSE_ON_EVENT:0 "イベントで一時停止しポップアップを表示"
 SETTING_PAUSE_ON_EVENT_TOOLTIP:0 "#T $SETTING_PAUSE_ON_EVENT$#!\nイベント発生時にゲームを一時停止し、ポップアップを表示します。"
 SETTINGS_CATEGORY_GAME_NOTIFICATIONS:0 "通知"
 SETTING_PAUSE_ON_EVENT_MESSAGE_SETTINGS:0 "$SETTING_PAUSE_ON_EVENT$ (シングルプレイのみ) "
 table_asset_cloth_theme:0 "テーブルクロス"
 table_asset_cloth_theme_desc:0 "コインが載せられている布。"
 RESET_SETTINGS_TO_DEFAULT:0 "#b デフォルト#!にリセット"
 SETTING_CULTURE_RELIGION_MINORITY_BLEND:0 "文化/宗教マップモードの少数派色混合"
 SETTING_CULTURE_RELIGION_MINORITY_BLEND_TOOLTIP:0 "#T $SETTING_CULTURE_RELIGION_MINORITY_BLEND$#!\n文化または宗教の概要マップモードにおいて、縞模様の代わりに少数派の色を混ぜ合わせた従来の表示を使用します。"
 SETTING_EVENT_OPTION_TEXT_ALIGNMENT:0 "イベント選択肢のテキストの配置"
 OPTION_LEFT:0 "左揃え"
 OPTION_CENTERED:0 "中央揃え"
 OPTION_RIGHT:0 "右揃え"
 DYNAMIC_THEME:0 "ダイナミック"
 DYNAMIC_THEME_DESC:0 "プレイした[concept_country]に基づき、自動で[ThemeCategory.GetName|v]のテーマを選択します"
 main_menu_image_theme:0 "メインメニュー画像"
 main_menu_image_theme_desc:0 "メインメニューの背景として表示されるアニメーション画像。"
