l_english:
 SETTINGS_PAGE_GRAPHICS: "Graphics"
 SETTINGS_PAGE_GAME: "Game"
 SETTINGS_PAGE_SYSTEM: "System"
 SETTINGS_PAGE_CONTROLS: "Controls"
 SETTINGS_PAGE_EDITOR: "Editor"
 SETTINGS_PAGE_INTERFACE: "Interface"
 SETTINGS_PAGE_AUDIO: "Audio"
 SETTINGS_CATEGORY_SCREEN: "Screen"
 SETTINGS_CATEGORY_QUALITY: "Quality"
 OPTION_EASY: "Easy"
 OPTION_NORMAL: "Normal"
 OPTION_HARD: "Hard"
 OPTION_NEVER: "Never"
 OPTION_MONTHLY: "Every month"
 OPTION_HALFYEAR: "Every half year"
 OPTION_YEARLY: "Every year"
 OPTION_FIVE_YEAR: "Every five years"
 OPTION_NO_AUTOSAVE: "Do not autosave"
 SETTINGS_CATEGORY_ACCOUNT: "Account"
 SETTINGS_CATEGORY_SYSTEM: "System"
 SETTINGS_CATEGORY_CONTROLS: "Controls"
 SETTINGS_CATEGORY_CAMERA: "Camera"
 SETTINGS_CATEGORY_AUDIO: "Audio"
 SETTINGS_CATEGORY_GUI: "GUI"
 SETTINGS_CATEGORY_INPUT_BINDINGS: "Input Bindings"
 DISCARD: "Discard"
 APPLY: "Apply"
 SAVE_AND_CLOSE: "OK"
 SETTINGS: "Settings"
 REQUIRES_RESTART: "Requires restart"
 REQUIRE_RESTART_DESCRIPTION: "Some settings will not take effect until you restart the game."
 SETTINGS_INPUT_REMAP_INPUT: "Remap input"
 SETTINGS_INPUT_CONFIRM: "Confirm"
 SETTINGS_INPUT_CANCEL: "Cancel"
 SETTINGS_INPUT_CLEAR: "Clear"
 SETTINGS_INPUT_SAVE_INPUT_PROFILE: "Save Profile"
 SETTINGS_INPUT_LOAD_INPUT_PROFILE: "Load Profile"
 SETTINGS_INPUT_RESET_INPUT_PROFILE: "Reset to Defaults"
 SETTINGS_INPUT_BINDING_TEXT: "Please choose an input binding for the action '$INPUT_ACTION$':\n\n$INPUT_NAME$"
 SETTINGS_INPUT_BINDING_WARNING_TEXT: "Warning: This input binding already exists for '$INPUT_ACTION$'!\nPressing '$SETTINGS_INPUT_CONFIRM$' will clear the old binding"
 SETTINGS_INPUT_BINDING_MODIFIERS_WARNING_TEXT: "Warning: input binding can not consist of only modifier keys"
