name: import_localization_files

on:
  repository_dispatch:
    types: [ import_localization_files ]
  workflow_dispatch:
    inputs:
      name:
        description: 'Description'
        required: false

jobs:
  build:
    runs-on: windows-2022
    strategy:
      matrix:
        python-version: [ 3.13.4 ]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Update pip
        run: python -m pip install --upgrade pip

      - name: Install requests
        run: pip install requests

      - name: Import localization files to paratranz
        run: |
          set PYTHONUTF8=1
          python import.py
        env:
          PARATRANZ_SECRET: ${{ secrets.PARATRANZ_SECRET }}
