name: validator

on: [pull_request]

jobs:
  valid_vic3_loca_job:
    runs-on: ubuntu-latest
    name: valid localization text format
    steps:
      - uses: actions/checkout@v3
      - uses: matanki-saito/pdx-txt-java@con-0.0.20
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          level: warning
          ROOT_DIR: ./source/JapaneseLanguageAdvancedMod/localization/
          TYPE: vic3loca
          
