l_japanese:
 SETTING_INPUT_CONTEXT_COMMON: "一般的"
 SETTING_INPUT_CONTEXT_COMMON_TOOLTIP: "一般的な入力コンテキスト用のキー割り当て"
 SETTING_INPUT_ACTION_PAUSE: "一時停止 / 一時停止解除"
 SETTING_INPUT_ACTION_INCREASE_SPEED: "速度を早める"
 SETTING_INPUT_ACTION_DECREASE_SPEED: "速度を遅くする"
 SETTING_INPUT_ACTION_SPEED_ONE: "速度1"
 SETTING_INPUT_ACTION_SPEED_TWO: "速度2"
 SETTING_INPUT_ACTION_SPEED_THREE: "速度3"
 SETTING_INPUT_ACTION_SPEED_FOUR: "速度4"
 SETTING_INPUT_ACTION_SPEED_FIVE: "速度5"
 SETTING_INPUT_ACTION_PLAY_PAUSE_MUSIC: "音楽の再生/一時停止"
 SETTING_INPUT_ACTION_NEXT_MUSIC_TRACK: "次の楽曲"
 SETTING_INPUT_ACTION_CAMERA_UP: "カメラ 上にパン"
 SETTING_INPUT_ACTION_CAMERA_LEFT: "カメラ 左にパン"
 SETTING_INPUT_ACTION_CAMERA_DOWN: "カメラ 下にパン"
 SETTING_INPUT_ACTION_CAMERA_RIGHT: "カメラ 右にパン"
 SETTING_INPUT_ACTION_LOCATION_FINDER: "ロケーションファインダー"
 SETTING_INPUT_ACTION_OPEN_POLITICS: "政策"
 SETTING_INPUT_ACTION_OPEN_BUDGET: "予算"
 SETTING_INPUT_ACTION_OPEN_BUILDINGS: "施設"
 SETTING_INPUT_ACTION_OPEN_MARKET: "市場"
 SETTING_INPUT_ACTION_OPEN_MILITARY: "軍事"
 SETTING_INPUT_ACTION_OPEN_DIPLOMATIC: "外交"
 SETTING_INPUT_ACTION_OPEN_TECHNOLOGY: "技術"
 SETTING_INPUT_ACTION_OPEN_CULTURE: "文化"
 SETTING_INPUT_ACTION_OPEN_POPULATION: "人口"
 SETTING_INPUT_ACTION_OPEN_JOURNAL: "ジャーナル"
 SETTING_INPUT_ACTION_OPEN_DECISIONS: "判断"
 SETTING_INPUT_ACTION_MAP_LIST: "台帳"
 SETTING_INPUT_ACTION_BACK: "戻る"
 SETTING_INPUT_ACTION_OPEN_OUTLINER: "アウトライナー"
 SETTING_INPUT_ACTION_TAB_1: "タブ1"
 SETTING_INPUT_ACTION_TAB_2: "タブ2"
 SETTING_INPUT_ACTION_TAB_3: "タブ3"
 SETTING_INPUT_ACTION_TAB_4: "タブ4"
 SETTING_INPUT_ACTION_TAB_5: "タブ5"
 SETTING_INPUT_ACTION_PRODUCTION_LENS: "生産レンズ"
 SETTING_INPUT_ACTION_POLITICAL_LENS: "政治レンズ"
 SETTING_INPUT_ACTION_DIPLOMATIC_LENS: "外交レンズ"
 SETTING_INPUT_ACTION_MILITARY_LENS: "軍事レンズ"
 SETTING_INPUT_ACTION_TRADE_LENS: "交易レンズ"
 SETTING_INPUT_ACTION_CONFIRM: "確認"
 SETTING_INPUT_ACTION_CURRENT_SITUATION: "現在の状況"
 SETTING_INPUT_ACTION_CONSTRUCTION_QUEUE: "建設キュー"
 SETTING_INPUT_ACTION_TOGGLE_CONSTRUCTION_QUEUE_PAUSE: "建設キューの一時停止/一時停止解除"
 SETTING_INPUT_ACTION_GO_TO_DETAILS: "詳細を表示"
 SETTING_INPUT_ACTION_SCROLL_UP: "上にスクロール"
 SETTING_INPUT_ACTION_SCROLL_DOWN: "下にスクロール"
 SETTING_INPUT_ACTION_TOGGLE_GUI_DEBUG: "(デバッグ) gui.debug"
