l_japanese:
 SETTING_INPUT_CONTEXT_COMMON:0 "一般的"
 SETTING_INPUT_CONTEXT_COMMON_TOOLTIP:1 "一般的な入力コンテキスト用のキー割り当て"

 SETTING_INPUT_ACTION_PAUSE:0 "一時停止 / 一時停止解除"
 SETTING_INPUT_ACTION_INCREASE_SPEED:0 "速度を早める"
 SETTING_INPUT_ACTION_DECREASE_SPEED:0 "速度を遅くする"
 SETTING_INPUT_ACTION_SPEED_ONE:0 "速度1"
 SETTING_INPUT_ACTION_SPEED_TWO:0 "速度2"
 SETTING_INPUT_ACTION_SPEED_THREE:0 "速度3"
 SETTING_INPUT_ACTION_SPEED_FOUR:0 "速度4"
 SETTING_INPUT_ACTION_SPEED_FIVE:0 "速度5"
 SETTING_INPUT_ACTION_PLAY_PAUSE_MUSIC:0 "音楽の再生/一時停止"
 SETTING_INPUT_ACTION_NEXT_MUSIC_TRACK:0 "次の楽曲"
 SETTING_INPUT_ACTION_CAMERA_UP:0 "カメラ 上にパン"
 SETTING_INPUT_ACTION_CAMERA_LEFT:0 "カメラ 左にパン"
 SETTING_INPUT_ACTION_CAMERA_DOWN:0 "カメラ 下にパン"
 SETTING_INPUT_ACTION_CAMERA_RIGHT:0 "カメラ 右にパン"
 SETTING_INPUT_ACTION_LOCATION_FINDER:0 "ロケーションファインダー"
 SETTING_INPUT_ACTION_OPEN_POLITICS:0 "政策"
 SETTING_INPUT_ACTION_OPEN_BUDGET:0 "予算"
 SETTING_INPUT_ACTION_OPEN_BUILDINGS:0 "施設"
 SETTING_INPUT_ACTION_OPEN_MARKET:0 "市場"
 SETTING_INPUT_ACTION_OPEN_MILITARY:0 "軍事"
 SETTING_INPUT_ACTION_OPEN_DIPLOMATIC:0 "外交"
 SETTING_INPUT_ACTION_OPEN_TECHNOLOGY:0 "技術"
 SETTING_INPUT_ACTION_OPEN_CULTURE:0 "文化"
 SETTING_INPUT_ACTION_OPEN_POPULATION:0 "人口"
 SETTING_INPUT_ACTION_OPEN_JOURNAL:0 "ジャーナル"
 SETTING_INPUT_ACTION_OPEN_DECISIONS:0 "判断"
 SETTING_INPUT_ACTION_MAP_LIST:0 "台帳"
 SETTING_INPUT_ACTION_BACK:0 "戻る"
 SETTING_INPUT_ACTION_OPEN_OUTLINER:0 "アウトライナー"
 SETTING_INPUT_ACTION_TAB_1:0 "タブ1"
 SETTING_INPUT_ACTION_TAB_2:0 "タブ2"
 SETTING_INPUT_ACTION_TAB_3:0 "タブ3"
 SETTING_INPUT_ACTION_TAB_4:0 "タブ4"
 SETTING_INPUT_ACTION_TAB_5:0 "タブ5"
 SETTING_INPUT_ACTION_PRODUCTION_LENS:0 "生産レンズ"
 SETTING_INPUT_ACTION_POLITICAL_LENS:0 "政治レンズ"
 SETTING_INPUT_ACTION_DIPLOMATIC_LENS:0 "外交レンズ"
 SETTING_INPUT_ACTION_MILITARY_LENS:0 "軍事レンズ"
 SETTING_INPUT_ACTION_TRADE_LENS:0 "交易レンズ"
 SETTING_INPUT_ACTION_CONFIRM:0 "確認"
 SETTING_INPUT_ACTION_CURRENT_SITUATION:0 "現在の状況"
 SETTING_INPUT_ACTION_CONSTRUCTION_QUEUE:0 "建設キュー"
 SETTING_INPUT_ACTION_TOGGLE_CONSTRUCTION_QUEUE_PAUSE:0 "建設キューの一時停止/一時停止解除"
 SETTING_INPUT_ACTION_GO_TO_DETAILS:0 "詳細を表示"
 SETTING_INPUT_ACTION_SCROLL_UP:0 "上にスクロール"
 SETTING_INPUT_ACTION_SCROLL_DOWN:0 "下にスクロール"
 SETTING_INPUT_ACTION_TOGGLE_GUI_DEBUG:0 "(デバッグ) gui.debug"
