l_japanese:
 SETTING_REFRACTION:0 "屈折"
 SETTING_REFRACTION_QUALITY:0 "屈折品質"
 SETTING_MAPOBJECT_QUALITY:0 "マップオブジェクト"
 SETTING_MAP_SSAO:0 "マップSSAO"
 SETTING_DOF:0 "被写界深度"
 SETTING_LENS_FLARE:0 ""
 SETTING_SECONDARY_LENS_FLARE:0 ""
